### ISSUE TITLE
Using on minio to speed up perf

### ISSUE THREAD

**Issue by ghost** [fwessels/tera-avx512#1]
I am using minio on a home backup setup and trying to make divergent drivers for hashing on different cpu's.
Have you tried this with minio yet.

**Comment by fwessels** [comment]
We have merged highwayhash into minio master, so for both Intel and ARM, this is by far the fastest hashing method.

**Comment by ghost** [comment]
thanks Frank. Just found it - great stuff.
Will play with the assembly stuff anyway - amazing stuff.
i have access to 512bit intel computer.

**Comment by fwessels** [comment]
You may also want to check out https://github.com/fwessels/hashcompare

Note that we looked at accelerating highwayhash for AVX512 but there is not much to gain there.

**Comment by ghost** [comment]
Ah good to know about the diminishing returns kicking in with 512 bits

Looked at the link. Thanks it's very well explained.

Highway hash at 10 GB/ sec per core is enough.
But what about the dsync problem with minio ! There is a limit of 16
servers in a cluster. It's because of the cap theirm choices made in that
you need it on 2 other nodes to be safe and then the rest are eventually
consistent.
I wonder if snowflake UUID that are using hybrid clocks to create sortable
UUID would allow you to relax the CAP properties and then know all nodes
will replicate the WAL and become eventually consistent.

Hybrid clocks are useful also for OT ( operational transform ). They are
using by cockroach DB to do multi Datacenter eventual consistency.

I know I am wafting on but we'll I think it can make minio more useful for
certain use cases. For example I make materialised views of data by
listening to events. Aka database triggers with materialised views.
